name: ci

on:
  push:
    branches:
      - master
  schedule: 
    - cron: "0 0 * * 1"


jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push PHP 7.3 image
        uses: docker/build-push-action@v2
        with:
          context: ./php7.3
          file: ./php7.3/Dockerfile
          push: true
          tags: repox/laravel-dev-php:7.3
