name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"


jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Nginx image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: repox/laravel-dev-nginx:latest
      - name: Build and push PHP image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php7,4/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            repox/laravel-dev-php:latest
            repox/laravel-dev-php:7.4
